resolver: lts-16.0

packages:
 - .

extra-deps:
  - gi-gtk-declarative-0.6.3
#  - gi-gtk-declarative-simple-0.6.3

# Override default flag values for local packages and extra-deps
# flags: {}

nix:
  enable: true
  packages:
    [ pkgconfig
    , gobject-introspection
    , gnome3.gtk
    ]

# Control whether we use the GHC we find on the path
# system-ghc: true

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
