resolver: nightly-2021-01-05

packages:
- .

extra-deps:
- git: git@github.com:guygastineau/gi-gtk-declarative.git
  commit: "04931ee8a4c3eaee994469d2379b50ede9cfbd56"
  subdirs:
  - gi-gtk-declarative
  - gi-gtk-declarative-app-simple
- evdev-2.0.0.1@sha256:f362b4f04b110fec974219acd4e5d86775a2771cf545ec16fff21bb6b97706f0,1444

# Override default flag values for local packages and extra-deps
# flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
compiler-check: newer-minor
